In [15]:
# Regular EDA and plotting libraries
import numpy as np  #tableaux et matrices
import pandas as pd # Permet de manipuler et d'analyser des données sous forme de dataframes, ce qui est similaire à des tableaux Excel
import matplotlib.pyplot as plt  #Permet de créer des visualisations de données, comme des graphiques et des diagrammes.
import seaborn as sns #  Permet de créer des visualisations de données plus complexes et plus attrayantes que celles fournies par matplotlib.

# We want our plots to appear in the notebook
# Afin de visualiser les graphiques dans le notebook
%matplotlib inline 

# Importation des métriques
from sklearn.metrics import accuracy_score


## Models
from sklearn.linear_model import LogisticRegression #implémenter le modèle de régression logistique
from sklearn.neighbors import KNeighborsClassifier # pour implémenter le modèle de plus proches voisins (KNN)
from sklearn.ensemble import RandomForestClassifier #implémenter le modèle de forêt d'arbres aléatoires (Random Forest)
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

## Model evaluators
from sklearn.model_selection import train_test_split, cross_val_score #utilisés pour diviser les données en ensembles d'entraînement et de test, et pour évaluer les modèles à l'aide de la validation croisée.
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV #pour ajuster les hyperparamètres des modèles.
from sklearn.metrics import confusion_matrix, classification_report # pour évaluer les performances des modèles de classification.
from sklearn.metrics import precision_score, recall_score, f1_score #pour évaluer les performances des modèles de classification.
from sklearn.metrics import RocCurveDisplay # new in Scikit-Learn 1.2+( utilisez une version antérieure de Scikit-Learn) #utilisé pour afficher la courbe ROC des modèles de classification.

# Print last updated
import time
print(f"Last updated: {time.asctime()}")

Last updated: Sat Apr 11 10:01:22 2026

In [16]:
df = pd.read_csv("heart_disease_dataset.csv") # 'DataFrame' shortened to 'df'  # charger le jeu de données 
df.shape # (rows, columns)  # afficher sa taille

(1000, 16)

In [17]:
df.describe()  # Donne des statistiques descriptives

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Heart Disease
count,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,52.293000,249.939000,135.2810,79.204000,4.529000,5.646000,134.941000,0.392000
std,15.727126,57.914673,26.3883,11.486092,2.934241,2.831024,36.699624,0.488441
min,25.000000,150.000000,90.0000,60.000000,0.000000,1.000000,70.000000,0.000000
25%,39.000000,200.000000,112.7500,70.000000,2.000000,3.000000,104.000000,0.000000
50%,52.000000,248.000000,136.0000,79.000000,4.500000,6.000000,135.000000,0.000000
75%,66.000000,299.000000,159.0000,89.000000,7.000000,8.000000,167.000000,1.000000
max,79.000000,349.000000,179.0000,99.000000,9.000000,10.000000,199.000000,1.000000

In [18]:
df.info()  # Affiche les informations sur les colonnes et les types de données

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB

In [19]:
df.dtypes  # Donne le type de données de chaque colonne

Age                         int64
Gender                     object
Cholesterol                 int64
Blood Pressure              int64
Heart Rate                  int64
Smoking                    object
Alcohol Intake             object
Exercise Hours              int64
Family History             object
Diabetes                   object
Obesity                    object
Stress Level                int64
Blood Sugar                 int64
Exercise Induced Angina    object
Chest Pain Type            object
Heart Disease               int64
dtype: object

In [20]:
#Afficher la somme des valeurs manquantes
df.isnull().sum()

Age                          0
Gender                       0
Cholesterol                  0
Blood Pressure               0
Heart Rate                   0
Smoking                      0
Alcohol Intake             340
Exercise Hours               0
Family History               0
Diabetes                     0
Obesity                      0
Stress Level                 0
Blood Sugar                  0
Exercise Induced Angina      0
Chest Pain Type              0
Heart Disease                0
dtype: int64

In [21]:
# Vérifier les doublons
duplicate_rows = df[df.duplicated()]
print("Nombre de lignes dupliquées:", duplicate_rows.shape[0])

Nombre de lignes dupliquées: 0

In [22]:
# Afficher les lignes dupliquées (optionnel)
print("Lignes dupliquées:")
print(duplicate_rows)

Lignes dupliquées:
Empty DataFrame
Columns: [Age, Gender, Cholesterol, Blood Pressure, Heart Rate, Smoking, Alcohol Intake, Exercise Hours, Family History, Diabetes, Obesity, Stress Level, Blood Sugar, Exercise Induced Angina, Chest Pain Type, Heart Disease]
Index: []

In [25]:
# And the top 10
df.head(10) #Cela affichera les 10 premières lignes du DataFrame

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0
5,77,Male,309,110,73,Never,NaN,0,No,Yes,Yes,4,122,Yes,Asymptomatic,1
6,64,Female,211,105,86,Former,Heavy,8,Yes,Yes,Yes,2,120,No,Typical Angina,1
7,60,Female,208,148,83,Never,Moderate,4,No,Yes,Yes,2,113,Yes,Asymptomatic,1
8,37,Female,317,137,66,Current,Heavy,3,No,Yes,Yes,5,114,No,Non-anginal Pain,0
9,63,Male,204,141,68,Former,Heavy,8,No,Yes,No,3,107,No,Asymptomatic,1

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB

In [27]:
df['Age'].unique()

array([75, 48, 53, 69, 62, 77, 64, 60, 37, 63, 67, 43, 44, 46, 45, 74, 76,
       58, 31, 66, 79, 32, 41, 36, 57, 72, 65, 28, 70, 51, 54, 52, 38, 25,
       55, 61, 30, 35, 42, 56, 47, 71, 68, 59, 33, 78, 26, 50, 27, 39, 40,
       29, 73, 49, 34])

In [28]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [29]:
df['Cholesterol'].unique()

array([228, 204, 234, 192, 172, 309, 211, 208, 317, 282, 293, 325, 155,
       226, 250, 279, 259, 246, 298, 297, 287, 177, 276, 265, 273, 197,
       319, 313, 179, 227, 262, 311, 230, 306, 216, 189, 162, 207, 271,
       209, 251, 268, 286, 167, 348, 330, 264, 252, 232, 261, 257, 339,
       166, 310, 180, 331, 307, 247, 243, 290, 223, 161, 241, 154, 203,
       205, 184, 291, 210, 215, 336, 242, 320, 284, 249, 248, 236, 174,
       164, 296, 278, 196, 272, 328, 176, 327, 217, 222, 185, 201, 237,
       175, 224, 294, 238, 270, 195, 281, 199, 345, 170, 256, 153, 183,
       347, 221, 200, 277, 302, 169, 329, 266, 198, 308, 283, 254, 343,
       292, 181, 231, 275, 168, 187, 323, 156, 235, 300, 344, 267, 178,
       159, 213, 255, 285, 335, 295, 158, 229, 349, 315, 326, 193, 191,
       341, 274, 214, 332, 212, 318, 280, 171, 337, 219, 322, 299, 244,
       333, 186, 342, 260, 289, 173, 324, 340, 151, 240, 163, 269, 220,
       188, 314, 338, 334, 194, 190, 258, 206, 157, 239, 245, 233, 304,
       321, 160, 301, 165, 288, 152, 303, 202, 346, 218, 316, 253, 225,
       150, 263, 305, 182, 312])

In [30]:
df['Blood Pressure'].unique()

array([119, 165,  91,  90, 163, 110, 105, 148, 137, 141, 108, 177, 169,
       168, 111, 173, 118,  97,  95, 117, 171, 159, 103, 170, 115, 154,
        98, 142, 158, 166, 150, 139, 143, 126, 162, 106, 128, 157, 129,
       125, 120, 107, 156, 135, 127, 122, 174, 161, 140, 121, 114, 144,
       132, 136, 101, 175, 109, 172, 138, 145, 149, 100, 124,  96, 179,
       155, 178, 152, 146, 164, 112, 167, 116, 153, 147, 130, 102,  93,
       133, 104, 151, 131, 176,  99, 160, 134, 123, 113,  94,  92])

In [29]:
df['Cholesterol'].unique()

array([228, 204, 234, 192, 172, 309, 211, 208, 317, 282, 293, 325, 155,
       226, 250, 279, 259, 246, 298, 297, 287, 177, 276, 265, 273, 197,
       319, 313, 179, 227, 262, 311, 230, 306, 216, 189, 162, 207, 271,
       209, 251, 268, 286, 167, 348, 330, 264, 252, 232, 261, 257, 339,
       166, 310, 180, 331, 307, 247, 243, 290, 223, 161, 241, 154, 203,
       205, 184, 291, 210, 215, 336, 242, 320, 284, 249, 248, 236, 174,
       164, 296, 278, 196, 272, 328, 176, 327, 217, 222, 185, 201, 237,
       175, 224, 294, 238, 270, 195, 281, 199, 345, 170, 256, 153, 183,
       347, 221, 200, 277, 302, 169, 329, 266, 198, 308, 283, 254, 343,
       292, 181, 231, 275, 168, 187, 323, 156, 235, 300, 344, 267, 178,
       159, 213, 255, 285, 335, 295, 158, 229, 349, 315, 326, 193, 191,
       341, 274, 214, 332, 212, 318, 280, 171, 337, 219, 322, 299, 244,
       333, 186, 342, 260, 289, 173, 324, 340, 151, 240, 163, 269, 220,
       188, 314, 338, 334, 194, 190, 258, 206, 157, 239, 245, 233, 304,
       321, 160, 301, 165, 288, 152, 303, 202, 346, 218, 316, 253, 225,
       150, 263, 305, 182, 312])

In [31]:
df['Heart Rate'].unique()

array([66, 62, 67, 72, 93, 73, 86, 83, 68, 87, 98, 81, 82, 99, 76, 70, 64,
       61, 63, 71, 78, 60, 92, 80, 79, 84, 97, 89, 91, 90, 77, 94, 75, 95,
       69, 74, 65, 96, 88, 85])

In [32]:
df['Smoking'].unique()

array(['Current', 'Never', 'Former'], dtype=object)

In [34]:
df['Alcohol Intake'].unique()

array(['Heavy', nan, 'Moderate'], dtype=object)

In [36]:
df['Exercise Hours'].unique()

array([1, 5, 3, 4, 6, 0, 8, 9, 7, 2])

In [37]:
df['Family History'].unique()

array(['No', 'Yes'], dtype=object)

In [38]:
df['Diabetes'].unique()

array(['No', 'Yes'], dtype=object)

In [39]:
df['Obesity'].unique()

array(['Yes', 'No'], dtype=object)

In [40]:
df['Stress Level'].unique()

array([ 8,  9,  5,  7,  2,  4,  3, 10,  1,  6])

In [41]:
df['Blood Sugar'].unique()

array([119,  70, 196, 107, 183, 122, 120, 113, 114,  85, 129, 192, 163,
        97, 121, 150,  76, 157, 139, 104, 112, 170, 187, 151,  92,  95,
       176, 166,  73,  75,  99, 111, 174, 135,  93, 109,  87, 137, 162,
        78, 160, 154, 172,  96, 180, 124, 152, 141,  88, 156, 177, 134,
       158,  86,  82, 105, 155,  74, 143, 127, 145, 198, 159, 148, 171,
       110, 103, 115, 193, 132, 140,  72, 147, 161, 144, 116,  90,  91,
        79, 173,  77, 142,  89, 178, 175, 118, 108, 149, 126, 101, 128,
       167, 184, 179, 197, 186, 146,  98,  84, 123,  94,  71, 181, 189,
       195, 138, 185, 106, 194, 188, 164, 102, 168, 169, 117, 165, 153,
       191, 136,  80, 133,  83, 199, 182, 100,  81, 131, 130, 190, 125])

In [42]:
df['Exercise Induced Angina'].unique()

array(['Yes', 'No'], dtype=object)

In [43]:
df['Chest Pain Type'].unique()

array(['Atypical Angina', 'Typical Angina', 'Non-anginal Pain',
       'Asymptomatic'], dtype=object)

In [44]:
df['Heart Disease'].unique()

array([1, 0])